Rails.application.routes.draw do
  get 'feature_info/index'
  get 'feature_info/show'
  get 'request_detail/index'
  get 'request_detail/show'
  get 'request_history/index'
  get 'request_history/show'
  get 'feature_request/index'
  get 'feature_request/show'
  get 'feature_edit/index'
  get 'feature_edit/show'
  get 'feature_edit/save'
  get 'zn_cus_customers/index'
  get 'zn_cus_customers/show'
  get 'zn_cus_customer_sites/index'
  get 'zn_cus_customer_sites/show'
  get 'zn_cus_scoped_features/index'
  get 'zn_cus_scoped_features/show'
  get 'ap_scoped_features/index'
  get 'ap_scoped_features/show'
  get 'feature_list/index'
  get 'feature_list/show'
  get 'fmg_features/index'
  get 'fmg_features/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
